version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: restaurant-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: restaurant-reservations
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - restaurant-dev-network

  # Backend API Service (Development)
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile.dev
    container_name: restaurant-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 4000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/restaurant-reservations?authSource=admin
      MONGODB_DB_NAME: restaurant-reservations
      JWT_SECRET: your-super-secret-jwt-key-for-development-only
      JWT_EXPIRES_IN: 24h
      CORS_ORIGIN: http://localhost:3000
      LOG_LEVEL: debug
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    volumes:
      - ./packages/backend:/app/packages/backend
      - ./packages/shared:/app/packages/shared
      - ./package.json:/app/package.json
      - /app/packages/backend/node_modules
    networks:
      - restaurant-dev-network

  # Frontend Web Application (Development)
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile.dev
    container_name: restaurant-frontend-dev
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:4000
      VITE_GRAPHQL_URL: http://localhost:4000/graphql
      VITE_NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - ./packages/shared:/app/packages/shared
      - ./package.json:/app/package.json
      - /app/packages/frontend/node_modules
    networks:
      - restaurant-dev-network

  # Redis (for caching and sessions)
  redis:
    image: redis:7.2-alpine
    container_name: restaurant-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - restaurant-dev-network
    command: redis-server --appendonly yes

  # MongoDB Express (Database Admin UI)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: restaurant-mongo-express-dev
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - restaurant-dev-network

volumes:
  mongodb_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  restaurant-dev-network:
    driver: bridge
